# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/api/'
    schedule:
      interval: 'weekly'
    groups:
      api:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/api_diagnostics/'
    schedule:
      interval: 'weekly'
    groups:
      api-diagnostics:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/dashboard/'
    schedule:
      interval: 'weekly'
    groups:
      dashboard:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      root:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/slackbot/'
    schedule:
      interval: 'weekly'
    groups:
      slackbot:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/speedtest/'
    schedule:
      interval: 'weekly'
    groups:
      speedtest:
        patterns:
          - '*'
