services:
  api:
    build:
      context: ./api
    command: 'uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 8000 --root-path /api --reload'
    volumes:
      - ./api:/app/api
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    expose:
      - '8000'
    restart: 'unless-stopped'
    environment:
      SERVER_IP: '${SERVER_IP}'
      LEETCODE_USERNAME: '${LEETCODE_USERNAME}'
      GITHUB_USERNAME: '${GITHUB_USERNAME}'
      OGP_IO_API_KEY: '${OGP_IO_API_KEY}'
      GA4_PROPERTY_ID: '${GA4_PROPERTY_ID}'
      NAS_IP: '${NAS_IP}'
      NAS_PORT: '${NAS_PORT}'
      NAS_API_USERNAME: '${NAS_API_USERNAME}'
      NAS_API_PASSWORD: '${NAS_API_PASSWORD}'
    secrets:
      - pihole_password
      - ga4_credentials
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.routers.api.rule=Host(`${SERVER_IP}`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.api.middlewares=api-stripprefix'
      - 'traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api'

  diagnostics_api:
    container_name: 'diagnostics_api'
    build:
      context: ./api_diagnostics
    command: 'uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 8000 --root-path /api/diagnostics --reload'
    environment:
      SERVER_IP: '${SERVER_IP}'
    volumes:
      - ./api_diagnostics:/app/api
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    expose:
      - '8000'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.diagnostics_api.entrypoints=web'
      - 'traefik.http.routers.diagnostics_api.rule=Host(`${SERVER_IP}`) && PathPrefix(`/api/diagnostics`)'
      - 'traefik.http.routers.diagnostics_api.middlewares=diagnostics_api-stripprefix'
      - 'traefik.http.middlewares.diagnostics_api-stripprefix.stripprefix.prefixes=/api/diagnostics'

  traefik:
    container_name: 'reverse_proxy'
    image: 'traefik:v2.10'
    command:
      # - "--log.level=DEBUG"
      - '--log.level=INFO'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:81'
    ports:
      - '81:81'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  whoami:
    container_name: 'whoami'
    image: 'traefik/whoami'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`${SERVER_IP}`) && PathPrefix(`/whoami`)'
      - 'traefik.http.routers.whoami.entrypoints=web'

  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard
      target: dev
    command: 'pnpm run dev'
    environment:
      # TODO: refactor
      API_BASE: 'http://${SERVER_IP}:81/api'
      SERVER_IP: '${SERVER_IP}'
      TRAEFIK_BASE: 'http://${SERVER_IP}:8080/dashboard'
      LEETCODE_USERNAME: '${LEETCODE_USERNAME}'
      GITHUB_USERNAME: '${GITHUB_USERNAME}'
    volumes:
      - './dashboard:/app'
      - 'exclude:/app/node_modules/'
    ports:
      - '5173:5173'
    restart: 'unless-stopped'

  cache:
    container_name: cache
    image: redis:alpine
    command: redis-server --save 60 1
    restart: 'unless-stopped'
    ports:
      - '6379:6379'

volumes:
  media:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NAS_IP},nolock,soft,rw'
      device: ':/volume1/media/'
  exclude:

secrets:
  pihole_password:
    file: './secrets/pihole_password.txt'
  slack_bot_token:
    file: './secrets/slack_bot_token.txt'
  slack_app_token:
    file: './secrets/slack_app_token.txt'
  ga4_credentials:
    file: './secrets/ga4_credentials.json'
