version: "3.8"

services:
  api:
    build: .
    command: "uvicorn api.main:api --host 0.0.0.0 --port 8080"
    volumes:
      - ./api:/app/api
    ports:
      - "8080:8080"
    restart: "unless-stopped"
