version: '3.9'

services:
  api:
    command: 'uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 8000 --root-path /api'

  dashboard:
    build:
      context: ./dashboard
      target: pro
    command: 'serve dist -s --listen 5173'
