services:
  api:
    command: 'uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 8000 --root-path /api'

  dashboard:
    build:
      context: ./dashboard
      target: pro
    # command: 'serve -l 5173 -l tcp://0.0.0.0:5173 -s dist'
    command: |
      sh -c "
      pnpm build &&
      serve -l 5173 -s dist
      "

  slack_bot:
    container_name: slack_bot
    build:
      context: ./slackbot
    command: 'python3 slackbot/main.py'
    volumes:
      - ./slackbot:/app/slackbot
    restart: 'unless-stopped'
    secrets:
      - slack_bot_token
      - slack_app_token

  speedtest:
    container_name: speedtest
    build:
      context: ./speedtest
    command: 'python3 -u main.py'

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Etc/UTC
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex:/config
      - media:/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '32400:32400'
    restart: 'unless-stopped'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - '53:53/tcp'
      - '53:53/udp'
      # Default HTTP Port
      - '84:80/tcp'
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - '443:443/tcp'
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Boise'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      WEBPASSWORD_FILE: pihole_password
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
