services:
  api:
    command: 'uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 8000 --root-path /api'

  dashboard:
    build:
      context: ./dashboard
      target: pro
    # command: 'serve -l 5173 -l tcp://0.0.0.0:5173 -s dist'
    command: |
      sh -c "
      pnpm build &&
      serve -l 5173 -s dist
      "

  slack_bot:
    container_name: slack_bot
    build:
      context: ./slackbot
    command: 'python3 slackbot/main.py'
    volumes:
      - ./slackbot:/app/slackbot
    restart: 'unless-stopped'
    secrets:
      - slack_bot_token
      - slack_app_token

  speedtest:
    container_name: speedtest
    build:
      context: ./speedtest
    command: 'python3 -u main.py'

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Etc/UTC
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex:/config
      - media:/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '32400:32400'
    restart: 'unless-stopped'
