name: 'Example JS/TS Actions'

on:
  push:
    branches:
      - '*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: noahtigner/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Noah Tigner'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  test-ts:
    runs-on: ubuntu-latest
    name: Test TS Action
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Test Local Action
        id: test-action
        uses: noahtigner/example-typescript-action@v0.2.1
        with:
          milliseconds: 1000
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
